### ISSUE TITLE
Store schema ID and version in Kafka message headers instead of payload prefix

### ISSUE THREAD

**Issue by nextropia** [hortonworks/registry#108]
The serde currently stores schema identifiers as a payload prefix. This makes the payload incompatible with standard Avro deserializers.

Since starting with 0.11 Kafka supports message headers, it is now possible to store schema identifiers in the headers and leave the payload unchanged.

Nice to have: the serde should be backward compatible and automatically detect the version of Kafka it is running against and store the identifiers either in headers or in the payload, depending on what's available.

**Comment by kamalcph** [comment]
#488 #491
