### ISSUE TITLE
Schema registry client in secured mode

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/registry#112]

**Comment by priyank5485** [comment]
Change SchemaRegistryClient such that if the server is running in secured mode using kerberos SPNEGO authentication then the calls to the server should succeed. Presumption is that java.security.auth.login.config should be set to a jaas config file that has a RegistryClient section in it. SchemaRegistryClient will use that section to populate the subject credentials and make every call to the server using that

**Comment by priyank5485** [comment]
https://github.com/hortonworks/registry/pull/113

**Comment by harshach** [comment]
Merged into master.
