### ISSUE TITLE
Make wire protocol more efficient.

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#131]
The selling point of using a schema registry is to reduce the bytes in flight, so that we can send data as efficient as possible as in large mass data throughput system every byte really counts, also to avoid the schema or meta data dwarfing the real data we want to send.

Currently wire protocol uses up 12 bytes for just identifying the schema of the data, when in fact in we have a unique 8 byte (int64 - java long) id available to us (SchemaVersionStorable id).

This could even be reduced just to 4 byte (int32 - java int) to reduce further by using one protocol id byte to send if the id < Int.Max (and just using 4 bytes) and another protocol id to send if the id > Int.Max (and then using 8 bytes)

Current: 
(protocolId = 0x1)
```
        byteArrayOutputStream.write(new byte[]{0x1});

        // 8 bytes : schema metadata Id
        // 4 bytes : schema version
        byteArrayOutputStream.write(ByteBuffer.allocate(12)
                                            .putLong(schemaIdVersion.getSchemaMetadataId())
                                            .putInt(schemaIdVersion.getVersion()).array());
```
Proposed:
(protocolId = 0x1, or 0x2)
```
if (SchemaVersionStorable.id < Int.max) {
        byteArrayOutputStream.write(new byte[]{0x1});

        // 4 bytes : schema version id (as int)
        byteArrayOutputStream.write(ByteBuffer.allocate(4)                
                                            .putInt( (int) SchemaVersionStorable.id).array());
} else {
        byteArrayOutputStream.write(new byte[]{0x2});

        // 8 bytes : schema version id (as long)
        byteArrayOutputStream.write(ByteBuffer.allocate(8)                
                                            .putLong( SchemaVersionStorable.id).array());
}
```
Saving 8 bytes!!!! when the id < Max.Int which in reality is unlikely to reach this man, but still we cater for incase.

**Comment by satishd** [comment]
@michaelandrepearce Thanks for bringing this issue. It was discussed earlier among ourselves before making this repo public and there was an internal JIRA filed. 

Custom protocol support is added to allow users have their own protocol and they do not necessarily use the default when it does not suit their needs.

Long can be avoided as it does not make much sense in reality for this usecase. Integer gives ~4.2billion numbers and 2,147,483,648 positive ids which means 21+ million schemas with 100 versions, very unlikely to reach this limit. We can even have logic to wrap to negative ids but that may be unnecessary.

**Comment by michaelandrepearce** [comment]
Agreed long can be avoided :) this is what this proposes.

But as the id in the schema repo is long, we should cater for it at least in the eventuality of something crazy occurring. We obviously avoid it in the serialisation by having it kept as an int if the number is of int scale, which obviously we hope it always should be.

**Comment by michaelandrepearce** [comment]
@satishd we agreed to align this then? and also benefit from the confluent protocol interop?

**Comment by satishd** [comment]
>@satishd we agreed to align this then? and also benefit from the confluent protocol interop?

@michaelandrepearce Right, we can have new protocol to address these issues.

>The other benefit of this, is mixing in with my other issue re compatibility with the confluent protocol ;) , i think really we want to make migration away as easy and as smooth as possible right? As in less barriers to entry increase the uptake (which I'm sure we want)

Right, we would like to have smooth and easy way to integrate current applications using confluent schema registry. Current protocol versioning support allows to support that, you may have observed  the current protocolid is 1 and confluent ser/des have version as 0 which we can accommodate to accept confluent related ser/des without any conflicts.

**Comment by satishd** [comment]
@michaelandrepearce I can pick this up if you have not already started working on this issue.

**Comment by michaelandrepearce** [comment]
@satishd Was awaiting the merge of the other PR, then went on long weekend leave. Was planning to do it this week. But if you wish to pick up happy for you to do so.

**Comment by satishd** [comment]
@michaelandrepearce I will pickup this and raise PR soon.

**Comment by michaelandrepearce** [comment]
@satishd great thanks, will look forward to review. Can you ping me/@ sign me when pr is raised

**Comment by satishd** [comment]
@michaelandrepearce Sure, I will do that.

**Comment by michaelandrepearce** [comment]
@satishd how did you progress on this?

**Comment by satishd** [comment]
@michaelandrepearce I was working on other issue about cleaning up APIs. It seems you are waiting for this change, I will make the respective changes today.

**Comment by michaelandrepearce** [comment]
@satishd yes we are.

Also obviously awaiting the next tag which would include this and all the confluent compatibility bits to be in a release version, when do we think we'd be spinning another release? end of this month?

**Comment by satishd** [comment]
@michaelandrepearce I have added 0.3.1 as next minor milestone. You can tag any issues you would need with that milestone. We can decide the target date based on the pending issues.
cc @harshach

**Comment by michaelandrepearce** [comment]
@satishd it seems i don't have the ability / permissions to add labels or select a milestone on issues.

**Comment by satishd** [comment]
@michaelandrepearce Added you to the list. Please let me know whether you are able to add labels/milestones on issues etc.

**Comment by satishd** [comment]
#150 addressed this issue.

**Comment by michaelandrepearce** [comment]
@satishd thanks, i am now able to, have done so.
