### ISSUE TITLE
Not able to add default value in schema once the schema is saved.

### ISSUE THREAD

**Issue by arunmahadevan** [hortonworks/registry#136]
1. Create a schema with some fields E.g.
```
{
 "type": "record",
 "name": "test",
 "namespace": "com.hortonworks.registries",
 "fields": [
  {
   "name": "business_id",
   "type": "string"
  }
 ]
}
```

2. Save

3. Click edit and now change the definition of field as 

```
  {
   "name": "business_id",
   "type": "string",
    "default": "x"
  }
```

4. Enter some description
5. Save

UI throws a message saying "Schema version already present" and does not save the changes.

**Comment by shahsank3t** [comment]
Verified from the UI, on making POST request, backend returns back the original(previously saved) schema's ID and is not creating new and so UI throws a warning message.

@satishd can you look at it, please?

**Comment by satishd** [comment]
Currently avro schema normalization does not take care of `default` attributes. I started a discussion in avro user/dev lists explaining the issue.

**Comment by satishd** [comment]
It seems there is a bug [AVRO-2002](https://issues.apache.org/jira/browse/AVRO-2002) already raised but given why it behaves so.

>Doug Cutting added a comment - 16/Feb/17 17:55
I believe you have misunderstood the semantics of fingerprints. Identical fingerprints mean that one schema can read output of the other without schema resolution, not that both can read a third using schema resolution.
Schema resolution permits interoperability (in some cases) between a pair of schemas whose fingerprints do not match. The SchemaCompatiblity class can determine whether a pair of schemas can, through resolution, interoperate.

I will address this issue extending avro schema normalization.
