### ISSUE TITLE
Add ability to validate schema compatibility without registering 

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#153]
Currently when editing a schema, you can only save or cancel. It would be good if you can check / validate compatibility without actually saving (e.g. a validate button), like wise it would be good if this was exposed feature via rest also.

**Comment by michaelandrepearce** [comment]
<img width="605" alt="screen shot 2017-06-20 at 15 41 53" src="https://user-images.githubusercontent.com/1387822/27339180-05351eda-55cf-11e7-854c-0054d327064c.png">

**Comment by satishd** [comment]
REST API exists to check compatibility with earlier versions of the given schema name.

For ex: 
```
curl -X POST --header 'Content-Type: application/json' --header 'Accept: application/json' -d '<schema-payload>' 'http://localhost:9090/api/v1/schemaregistry/schemas/<schema-name>/compatibility'
```

+1 to have validate on UI.

**Comment by shahsank3t** [comment]
@michaelandrepearce @satishd 
Currently, on clicking save, we are showing an error message if compatibility fails.
<img width="1060" alt="screen shot 2017-07-03 at 3 57 08 pm" src="https://user-images.githubusercontent.com/6761317/27789023-6d80ff98-6008-11e7-98b7-55a63b140d54.png">

I don't see any use of adding another button "validate" and asking user to validate first and then save when the same things are happening on single click(Save button) right now.

cc: @harshach

**Comment by shahsank3t** [comment]
IMO, UI should be showing proper error message than just the hardcoded message.

For example: in the above image, backend does return an error message saying `"Reader schema missing default value for field: firstname"` which seems to be meaningful and appropriate but we are not showing on UI.

@satishwaghela can you please make this error message change and raise a PR.

**Comment by satishd** [comment]
@shahsank3t I guess the enhancement asked here is not to remove save and add validate then save but having UI to check whether a specific schema is compatible with earlier versions of the schema or not without adding it. This allows users to update schema  and in between they can check whether current changes are valid or not.

**Comment by shahsank3t** [comment]
@satishd 
> This allows users to update schema and in between they can check whether current changes are valid or not.

Ah ok. Didn't think about such scenario. I was under impression that user might add full schema and just save. But this is completely valid and good thing to have when user will add/remove fields, validate and then go further adding/removing other fields before saving the actual schema.

**Comment by satishwaghela** [comment]
Raised PR https://github.com/hortonworks/registry/pull/178 for UI enhancement
