### ISSUE TITLE
Release Registry 0.3.0

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/registry#170]
Seems like we start assigning issues to 0.3.1 and 0.3.2, and issues for 0.3.0 are all closed.

Given that Streamline still depends on Registry 0.3.0-SNAPSHOT, it would be ideal to release Registry 0.3.0 to avoid depending on SNAPSHOT version.

**Comment by michaelandrepearce** [comment]
+1 I think this is fair, I do think just finishing the open PR for issue 130 would be a nice as it's almost ready to merge.

**Comment by satishd** [comment]
Closing this as this is published as tag/release.
