### ISSUE TITLE
Add Validate Latest option while adding new schema versions.

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#171]
This issue is raised to address [discussion](https://github.com/hortonworks/registry/issues/166#issuecomment-311861229) happened on #166.

This was needed for Confluent SR migration as it has an option only to validate against earlier schema. This should not be the default behavior and a good practice is to have the option set as validate against all earlier versions of the schema. 
Current behavior of validating against all earlier versions of the schema continues to be the default option.

**Comment by michaelandrepearce** [comment]
@satishd should add the need/ability to change the compatibility setting with this

**Comment by satishd** [comment]
@michaelandrepearce I started working on this yesterday evening but I got a notification later about  PR addressing this issue. Please send an email to registry-group or assign issue to yourself when you plan to work on any issues so that there will not be any duplicate work from others. I also should have done the same. :)

Thanks for raising the PR.
