### ISSUE TITLE
Add ability to delete / disable an individual schema version

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#172]
Where a schema has accidentally been registered, especially in development/testing environments, we need an ability to regress the registration either by disabling the schema registered (which means this schema no longer included in future validations) or by supporting deletion entirely.

This can be done by hacking the JDBC layer and restarting, but really an elegant support solution should exist.

**Comment by michaelandrepearce** [comment]
I favour the disabling approach btw

**Comment by michaelandrepearce** [comment]
See PR : https://github.com/hortonworks/registry/pull/174

Would be good to expose a "disable" button on the Front End (at both the schema and version levels), but my FE skills are lacking.

**Comment by satishd** [comment]
@michaelandrepearce Can we close this as this issue is addressed as part of schema version lifecycle state management? Pl file a separate issue if we need to add any other usecases.
