### ISSUE TITLE
Add ability to delete / disable a Schema

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#173]
When a kafka topic is cleaned (deleted) entirely (e.g. even data is removed), it should be possible to remove the corresponding schema entirely, this could be done either by disabling all existing versions (so that they still exist but no longer act in any future validation or able to be used for future data producing), or by deletion of these entirely.

**Comment by michaelandrepearce** [comment]
I favour the disabling approach btw. And would work with neatly with https://github.com/hortonworks/registry/issues/172, if same approach used, as would just get all versions and cycle through disabling.

**Comment by michaelandrepearce** [comment]
See PR : #174

**Comment by satishd** [comment]
@michaelandrepearce Can we close this as this issue is addressed as part of schema version lifecycle state management? Pl file a separate issue if we need to add any other usecases.

**Comment by michaelandrepearce** [comment]
Agreed closing
