### ISSUE TITLE
Add life cycle management of schemas.

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#177]
This should address schema/versions life cycle management  
- adding multiple versions of schema with different states
    - created/published/disabled/archived/deleted
    and there should be a way to plugin any custom states in between for user specific scenarios.
- updating schema metadata including compatibility levels
and much more. Wiki/doc will be created to discuss the intended design and it can be discussed further to address as many usecases.

Doc is located at https://goo.gl/JhE7pb

**Comment by michaelandrepearce** [comment]
@satishd any more detail on this? if not can we progress with disable feature for the interim?

**Comment by satishd** [comment]
@michaelandrepearce I will put up a doc with our initial thoughts by tomorrow in which we can discuss.

**Comment by michaelandrepearce** [comment]
@satishd thanks.

**Comment by satishd** [comment]
Initial version of the doc is located at https://goo.gl/fcDWfc

**Comment by satishd** [comment]
@michaelandrepearce You may want to go through the doc https://goo.gl/JhE7pb and put your comments.

**Comment by michaelandrepearce** [comment]
Comments I have are:

It's not clear what states a version schema is included in validation of new schemas or not. (E.g. Our pr disabled means the schema no longer looked at in regards to forward/backwards validation checks)

It's not clear at what stages a schema can be used to produce data for/consume, e.g if in disabled state I shouldn't be able to produce, but if data was produced before disabling then I should stilll be able to consume/deserialise as the schema for an Id exists.

There is no flow to delete once a schema is enabled, I am fine with this depending on the above details. Though others may not be, I think it should bad able to delete.

How does this fit with self registering like Kafka serdes currently? Do they instantly go into enabled? This should be stated.

The branching section just looks like git models, at this stage is this complexity really needed? I fear this may cause more issues than it solves.

Is there rbac controls for the review flows / branching? (Sso, ldap, Kerberos, saml integrated)

Are we looking to implement this incrementally? E.g. We could do initialised, enabled, disabled easily now before the more complex bits.

**Comment by michaelandrepearce** [comment]
I was thinking on the flow bits re branching reviews etc, maybe just make this backenable to a git repo rather than having to code

**Comment by michaelandrepearce** [comment]
Wrong button sorry

**Comment by satishd** [comment]
>It's not clear what states a version schema is included in validation of new schemas or not. (E.g. Our pr disabled means the schema no longer looked at in regards to forward/backwards validation checks)

Validation should be done for that branch either with all versions or with latest based on configured validation level. 

>It's not clear at what stages a schema can be used to produce data for/consume, e.g if in disabled state I shouldn't be able to produce, but if data was produced before disabling then I should still be able to consume/deserialise as the schema for an Id exists.

Schemas can be used as long as they are enabled. While consumption, when messages are received with disabled schemas they will still be deserialized with disabled writer schemas but when the reader schema is disabled then an exception will be thrown.

>There is no flow to delete once a schema is enabled, I am fine with this depending on the above details. Though others may not be, I think it should bad able to delete.

Once a schema is enabled, it can be archived but not to be deleted to see the complete history of changes. 

>How does this fit with self registering like Kafka serdes currently? Do they instantly go into enabled? This should be stated.

Right, they are instantly enabled. Schema metadata can have options on which users can be given such authorization etc but that is out of scope for now. 

>Is there rbac controls for the review flows / branching? (Sso, ldap, Kerberos, saml integrated)

This is out of scope for now, we can give a way where user can plugin their own auth mechanism. This will be part of authorization which is in the roadmap.

>The branching section just looks like git models, at this stage is this complexity really needed? I fear this may cause more issues than it solves. At most it think it should only be for the left hand side of the flow tree during reviews etc, e.g initialised enabled disabled archived really should be linear only.

Right this is similar to git models. This solves use cases like schema is going through changes in dev environment and that should not effect the master branch till that schema is finalized after going through different development cycles. Linkedin folks sent a mail in registry group with their use case mentioned [here](https://groups.google.com/forum/#!topic/registry/vzhOApZqwXY). If you have branching then you may not be required to disable/delete intermediate versions in the master branch without affecting other running applications in respective environments as they are based out of respective branches.

**Comment by michaelandrepearce** [comment]
@satishd the first query isn't answered. Are disabled/archived schemas included in validation. I expect they're not. But thus needs to be clear

**Comment by satishd** [comment]
@michaelandrepearce Right, they should not be included in validation as long as they are disabled/archived.

Do we really need to  give a way to enable a disabled schema? I think below flow is simpler
 enable ---> disable ---> archive(soft-delete)
I would like to have the default state flow restrictive but that can be extendable if needed by users plugging in their own states in between.

**Comment by michaelandrepearce** [comment]
> Do we really need to give a way to enable a disabled schema? I think below flow is simpler
enable ---> disable ---> archive(soft-delete)
I would like to have the default state flow restrictive but that can be extendable if needed by users plugging in their own states in between.

Your doc shows a re-enable flow. TBH I think it's needed for case of accidental disabling

**Comment by satishd** [comment]
Right, I kept that to enable any disabled schema versions but I was trying to find any specific usecases other than accidental disabling. When it is enabled again it should be compatible based on validation level with earlier and further versions.

**Comment by michaelandrepearce** [comment]
@satishd thanks. Based on the replies in general I think this should work for us. If we could update the doc to reflect/make more clear this conversation then it's a +1

**Comment by satishd** [comment]
@michaelandrepearce I have updated the doc to make some of the points more clear as we had discussed. You can let me know or update the doc if you find anything missing.

**Comment by michaelandrepearce** [comment]
Sorry for the delay updated doc looks good to me.

+1

**Comment by satishd** [comment]
Closing this as it is resolved by PRs tagged earlier.
