### ISSUE TITLE
DefaultSchemaRegistry#getSchemaVersionInfo should be aligned with API contract

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#191]

**Comment by harshach** [comment]
@satishd can you please add more details.

**Comment by satishd** [comment]
@harshach `DefaultSchemaRegistry#getSchemaVersionInfo(String schemaName, String schemaText)` throws `SchemaNotFoundException` when there is no schema with the given schemaText instead of returning null which java doc says. This is a minor change and have no change with user api.

Raised #192 for this issue.
