### ISSUE TITLE
Provide command line tool to delete a schema

### ISSUE THREAD

**Issue by harshach** [hortonworks/registry#198]
We've a full life cycle management thats being worked upon here https://github.com/hortonworks/registry/issues/177 . But current users requesting a way to delete a schema. Until the ISSUE-177 is resolved we should provide a tool to accept the schema name or id to delete it from backend database. This will provide temporary option while we finish ISSUE-177

**Comment by michaelandrepearce** [comment]
Could this not be exposed as a temporary rest endpoint. So it's also cleared from server caches

**Comment by michaelandrepearce** [comment]
Or even merge in https://github.com/hortonworks/registry/pull/174 as a temporary measure
