### ISSUE TITLE
UI not able to display the right schema version number after deletion

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/registry#205]
Let us assume that we have 4 version for schema "schema1" viz, 1,2,3 and 4. If I delete version 3 and refresh the UI, the UI is showing available versions for "schema1" as 1,2 and 3 instead of 1,2 and 4, i.e version 4 is presented as version 3 in the UI. I came across this issue while testing the pull request #204

**Comment by shahsank3t** [comment]
@satishd @raju-saravanan I'll look into this issue today and meanwhile do we also want to expose a button on UI to delete a particular version of schema or it's just a backend thing?

cc: @harshach

**Comment by satishd** [comment]
@shahsank3t Ideally, delete operation should be enabled with some authorizations. #177 may give in which state schema version can be allowed to be deleted. But that can be addressed once #177 is done.
@harshach We may have delete button schema versions for now as users are asking for it but users should understand that the existing consumers of that schema will be affected if it is deleted. We can have proper way to archive/delete once we have #177 along with authorizations configured for a user.

**Comment by satishd** [comment]
Closing this as #210 addresses the raised issue.

**Comment by michaelandrepearce** [comment]
+1 having a temporary button in the UI
