### ISSUE TITLE
Support for schema type: JSON

### ISSUE THREAD

**Issue by eparisca** [hortonworks/registry#231]
Hello,

We are test-driving Schema Registry and really like it. According to http://registry-project.readthedocs.io/en/latest/competition.html Hortonworks' Registry supports (or will support) JSON schema. When are you expecting to add support for JSON Schema? 

Thank you

**Comment by satishd** [comment]
@eparisca Thanks for your interest in this project. JSON schema is not supported yet, but it can be added with the existing framework in a similar way it is done for Avro. You can raise respective Github issues after going through the code. You can also let us know if you need any help in getting started with that.

**Comment by eparisca** [comment]
@satishd I would love to help. How do I get started? Any special recommendations? 

I'm already walking through the Avro code in the framework in registry/schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/avro/

Looking at https://github.com/everit-org/json-schema as a potential good fit for the Schema validator. Thoughts? 

Thank you.

**Comment by satishd** [comment]
@eparisca Good that you are going through avro support implementation in registry. You need to implement [SchemaProvider](https://github.com/hortonworks/registry/blob/master/schema-registry/common/src/main/java/com/hortonworks/registries/schemaregistry/SchemaProvider.java) for jsons and register as it is done for avro [here](https://github.com/hortonworks/registry/blob/master/conf/registry.yaml#L7)

You can start with implementing SchemaProvider to address the below
- checking for compatibility between versions.
- generating finger print using normalized form of schema.
- generating resultant schema if it supports any schema imports/includes.
- effective serialization/deserializtion of json payloads.

You can start exploring either  jackson based or https://github.com/everit-org/json-schema for validator etc.

**Comment by kkarthikpsgtech** [comment]
@eparisca , Are you looking into this?

**Comment by eparisca** [comment]
@kkarthikpsgtech No, sorry. I took a new job and am no longer using Schema Registry.

**Comment by kkarthikpsgtech** [comment]
@satishd can you assign this ticket to myself? I have started working on it

**Comment by kkarthikpsgtech** [comment]
Any update on this?

**Comment by satishd** [comment]
@kkarthikpsgtech We have no plans to review/support json schema provider in near future.

**Comment by hanhongfang** [comment]
Could you kindly clarify what the scheme types are supported in lastest 0.8.0 RC3 release? 
- From this page https://registry-project.readthedocs.io/en/latest/competition.html, I see registry supports AVRO/PROTOBUF/JSON
- But this JIRA is still open.

**Comment by lccbiluox2** [comment]
Can you support JSON in any format?

**Comment by lccbiluox2** [comment]
{
	"field": [{
		"name": "age",
		"type": "string"
	}, {
		"name": "name",
		"type": "string"
	}]
}

**Comment by lccbiluox2** [comment]
{"hello":"world"}
