### ISSUE TITLE
Port UI from react.js to vue.js due to licensing issue

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/registry#235]
Since Apache Software Foundation has decided 'Facebook BSD+Patents License' is no longer allowed to be used as a direct dependency in Apache projects, and Facebook too has decided to not change their license, we need to remove react.js and all other libraries that have its licensing and thereby replacing it with Vue.js (MIT license).

For reference: https://github.com/facebook/react/issues/10191

**Comment by rasgg** [comment]
Facebook decided to [relicense react.js](https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/) under MIT license, I believe this issue can be closed.

**Comment by shahsank3t** [comment]
@rasgg Yes, closing this issue.
