### ISSUE TITLE
Schema Registry Install fails with mariaDB backed database

### ISSUE THREAD

**Issue by prakashsu** [hortonworks/registry#236]
Schema Registry Install fails with mariaDB backed database.

HDF Version :- 3.0
mariaDB Version :- 10.0.28

VARCHAR(255) instead of VARCHAR(256) 

Attached the error log

**Comment by prakashsu** [comment]
![image002](https://user-images.githubusercontent.com/31223743/29538119-edc964a4-8689-11e7-9913-c52fcc7454f2.png)

Attached error.

**Comment by satishd** [comment]
@prakashsu  Can you try with latest master branch or you can change VARCHAR(256) with VARCHAR(255) in the existing sql file?

**Comment by prakashsu** [comment]
@satishd yes Changing the VARCHAR(256) with VARCHAR(255) works . SAM and Schema Registry got installed after changing the DDL to VARCHAR(255).
