### ISSUE TITLE
Postgres and MySQL database schema mismatch

### ISSUE THREAD

**Issue by apsaltis** [hortonworks/registry#241]
When using Postgres as the backing store any attempt to add a schema fails. The root cause of this is a discrepancy in the schema_version_state table between MySQL and Postgres. The MySQL definition is:

> CREATE TABLE IF NOT EXISTS schema_version_state (
>   id              BIGINT AUTO_INCREMENT NOT NULL,
>   schemaVersionId BIGINT                NOT NULL,
>   stateId         TINYINT               NOT NULL,
>   sequence        INT                   NOT NULL,
>   timestamp       BIGINT                NOT NULL,
>   **details         VARCHAR(255),**
>   PRIMARY KEY (schemaVersionId, stateId, sequence),
>   UNIQUE KEY (id)
> );

And the Postgres one is:

> CREATE TABLE IF NOT EXISTS schema_version_state (
>   "id"              SERIAL UNIQUE NOT NULL,
>   "schemaVersionId" BIGINT        NOT NULL,
>   "stateId"         SMALLINT       NOT NULL,
>   "sequence"        INT           NOT NULL,
>   "timestamp"       BIGINT        NOT NULL,
>   **"details"         VARCHAR(255)  NOT NULL,**
>   PRIMARY KEY ("schemaVersionId", "stateId", "sequence"),
>   UNIQUE ("id")
> );
> 

The key difference that causes a problem is the `details` column. For MySQL, it is allowed to be NULL and in the Postgres version, it is set as NOT NULL.

The corresponding code in `storeSchemaVersionState` does not set the details field of the `SchemaVersionStateStorable` object. The result is the insert fails, incidentally, this is not logged, but if you are in the psql console then you will see an error like the following:

`postgres=# ERROR:  null value in column "details" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 5, 2, 1504826519450, null).
STATEMENT:  INSERT INTO schema_version_state ("schemaVersionId", "sequence", "stateId", "timestamp", "details") VALUES( $1,$2,$3,$4,$5)
	RETURNING *`

To fix this we can:
- update the table definitions
- update the `storeSchemaVersionState` code to set the `details`

Just synching the table definitions to allow the `details` to be NULL is a quick fix. However, it seems like we may want to have the details recorded. 

I have fixes and test cases for both, let me know if I should submit a P/R for this.

**Comment by satishd** [comment]
@apsaltis Thanks for reporting this issue. `details` field is not mandatory, it is upto the state to store any info if they need. No inbuilt state currently uses this, but we want to change the type of details to BLOB as having VARCHAR(255) may be too restrictive for custom states. You can raise PR by updating the script by removing NOT NULL for details field for postgres.
