### ISSUE TITLE
A new tag/release has occured same release version of 0.3.0 and overwritten.

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#248]
A new/tag release has occured, that has overriden the previous 0.3.0 version (seemingly it seems this tag just made is current master head), which also now has changes since the original 0.3.0 tag done and voted in end of July, can we fix this please and correct that the tag 0.3.0 is the original code state as a tag is meant to be immutable, and the just made new one should be 0.3.1 if you need a cut of master

**Comment by michaelandrepearce** [comment]
@harshach @satishd please can this be resolved asap!

**Comment by satishd** [comment]
@michaelandrepearce I guess this issue is resolved. Pl let me know if there are still some issues with that tag/release.

**Comment by michaelandrepearce** [comment]
@satishd I believe it is also
