### ISSUE TITLE
Confluent SR incompatibility for versions/latest and versions/{versionId}

### ISSUE THREAD

**Issue by apsaltis** [hortonworks/registry#249]
For the following REST requests, we are not compatible with the Confluent SR. 

`GET     /api/v1/confluent/subjects/{subject}/versions/latest`

The HWX Schema Registry was returning this
`{"name":"topic1-value","version":3,"schema":"{\"type\":\"record\",\"name\":\"myrecord\",\"fields\":[{\"name\":\"f1\",\"type\":\"string\"}]}"}`
 
Confluent Returns this:
`{"subject":"topic1-value","version":1,"id":2,"schema":"{\"type\":\"record\",\"name\":\"myrecord\",\"fields\":[{\"name\":\"f1\",\"type\":\"string\"}]}"}`
 
The missing id caused deserialization issues.

`GET     /api/v1/confluent/subjects/{subject}/versions/{versionId}`

If you take the example JSON from above and use `3` for the version id, the calls fails. This is caused by the SR using the metadata ID internally not the versionId to retrieve the schema from cache and/or storage.

**Comment by satishd** [comment]
@apsaltis This API is built based on Confluent API doc mentioned  [here](https://goo.gl/M1yFui)

```
GET /subjects/(string: subject)/versions/(versionId: version)

Parameters: 
- subject (string) – Name of the subject
- version (versionId) – Version of the schema to be returned. Valid values for versionId are between [1,2^31-1] or the string “latest”. “latest” returns the last registered schema under the specified subject. Note that there may be a new latest schema that gets registered right after this request is served.

Response JSON Object:
- name (string) – Name of the subject that this schema is registered under
- version (int) – Version of the returned schema
- schema (string) – The Avro schema string

Status Codes: 
- 404 Not Found 
     40401 – Subject not found 
     40402 – Version not found
- 422 Unprocessable Entity 
     42202 – Invalid version
- 500 Internal Server Error 
     50001 – Error in the backend data store

```

**Comment by apsaltis** [comment]
@satishd -- 
I think there are several issues here:
1. You are 100% correct that the API documentation matches the JSON we are returning when an using "latest" as the versionID. However, I based my findings on using a Confluent Schema registry consumer and using the Confluent API directly. So the Confluent docs do not match the API.

2. In the case of using an explicit versionId, the HWX SR would fail or return the wrong JSON as internally the wrong ID was being used to retrieve the schema.

**Comment by satishd** [comment]
@apsaltis These changes break existing tests, can you fix those tests with the proposed changes?

```
ests in error:
  ConfluentRegistryCompatibleResourceTest.stressTestConfluentApis:101->doTestAPIsMixWithIncompatibleInvalidSchemas:152->getVersion:323 » NotFound
  ConfluentRegistryCompatibleResourceTest.testConfluentApis:192->getVersion:324 » UnrecognizedProperty
  ConfluentRegistryCompatibleResourceTest.testConfluentBasicApisMixWithInvalidIncompatibleSchemas:128->doTestAPIsMixWithIncompatibleInvalidSchemas:152->getVersion:323 » NotFound
  ConfluentRegistryCompatibleResourceTest.testSubjectWithVersionIdApi:230 » UnrecognizedProperty

Tests run: 64, Failures: 0, Errors: 4, Skipped: 0
```

**Comment by apsaltis** [comment]
@satishd -- Sorry -- terrible oversight on my part. Let me fix those.
