### ISSUE TITLE
Improve the commit process

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/registry#263]
Recently, Streamline project got an improved commit process via defining some policies and introducing merge script.
You can refer the issue from https://github.com/hortonworks/streamline/issues/923 and pull request from https://github.com/hortonworks/streamline/pull/930.

We could apply same process (or similar) to Registry project to help merger remedy the pain to merge, and hopefully remove unmaintained CHANGELOG file.

**Comment by satishd** [comment]
@HeartSaVioR Thanks for raising and working on this issue. We do not have changelog file in registry and following guideline of commit messages with respective github issues mostly.

**Comment by satishd** [comment]
@HeartSaVioR I have added DEVELOPER.md like streamline into master branch, you can add merge script details into the doc.
