### ISSUE TITLE
Support transactional semantics in storage manager.

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#273]

**Comment by raju-saravanan** [comment]
At a basic level the transaction is carried out in the following manner

   1) Get a new connection and set AutoCommit as false
   2) Use the connection for a series of DDL and DML statements
   3) If there are no errrors then, Connection.commit()
   4) Else, Connection.rollback();

 A transaction will be supported at a thread level, i.e transaction will be attached to a thread. I will be creating following classes to achieve this,
   * TransactionBookKeeper :- This will be a singleton, will have a ConcurrentMap mapping a threadId to a connection
   * TransactionalStorage  :- This will be a interface extending StorageManager, exposing beginTransaction(), rollBackTransaction() and commitTransaction(), 
   							  this will be implemented by storageManager that supports transaction ex:- JDBCStroageManager.
   * TransactionManager    :- This will take a StorageManager in its constructor, expose beginTransaction(), rollBackTransaction() 
   							  and commitTransaction() for the application code to consume, which will be internally be mapped to the StorageManager's 
   							  corresponding methods. This is will have a check to see if its an instance of TransactionalStorage,
   							  if not it will ignore the call to manipulate a transaction, else it will invoke the corresponding methods from the TransactionalStorage.

At the resouce level, transactionManager will be used to control a transaction like so,

try {
 	transactionManager.beginTransaction();
 	...
 	transactionManager.commitTransaction();
} catch(Exception e) {
	transactionManager.rollback();
	throw e;
}

Each of this transactionManager's functions will map it to its corresponding transactionalStorage's functions. This is what the functions will do,
   * beginTransaction()    :- get a new connection, set it to autoCommit false, and makes an entry in TransactionBookKeeper
   * rollBackTransaciont() :- get the connection attached to the currentThreadId, rollbacks the transaction, removes the entry for this threadId in the TransactionBookKeeper, 
   							  set the setAutoCommit as true and returns the connection to the pool.
   * commitTransaction()   :- get the connection attached to the currentThreadId, commits the transaction, removes the entry for this threadId in the TransactionBookKeeper, 
   							  set the setAutoCommit as true and returns the connection to the pool.

In AbstractQueryExecutor, we have a method getConnection(), which is used by all the ddl and dml statements to fetch a connection. Now, the method will check with TransactionBookKeeper 
to see if there are an entry for the currentThreadId, if so it will get the connection associated with the threadId, else it will fetch a new connection. Hence, once a beginTransaction is invoked,
every DDL and DML statements will use the connection, until its entry is removed from TransactionBookKeeper either using rollBackTransaction() or commitTransaction().

**Comment by arunmahadevan** [comment]
The approach looks good. You may want to explore if we can do without modifying every resource method and introducing the try catch blocks. E.g look at the `@UnitOfWork` annotation provided by [dropwizard-hibernate](http://www.dropwizard.io/1.2.0/docs/manual/hibernate.html#transactional-resource-methods) and see if we can do something similar. It seems to make use of the application event listener - [here](https://github.com/dropwizard/dropwizard/blob/master/dropwizard-hibernate/src/main/java/io/dropwizard/hibernate/UnitOfWorkApplicationListener.java)

**Comment by satishd** [comment]
@raju-saravanan Thanks for putting the notes describing the approach here. 
Overall approach LGTM. But I may have few comments on how we want to store connections with threads etc which I will raise in PR. 
You can raise PR with the basic functionality without waiting till additional annotation utilities to wrap code in beginTx to commit/RollbackTx is added so that review of basic functionality can happen in parallel while you add other utility.

**Comment by satishd** [comment]
Closing this issue as #286 resolved it.
