### ISSUE TITLE
Schema (size) is limited by underlying meta store data type 

### ISSUE THREAD

**Issue by rtempleton** [hortonworks/registry#287]
Using MySQL db for SR, customer is attempting to register a schema > 65,000 characters. The schema_version_info table stores the schema in the schemaText field which is set to TEXT data type and we were getting truncation errors attempting to register such a large schema. Ran the following alter table to increase the size: ALTER TABLE schema_version_info MODIFY schemaText MEDIUMTEXT;

**Comment by michaelandrepearce** [comment]
Would it be best to maybe even store it as a CLOB or BLOB

**Comment by priyank5485** [comment]
https://github.com/hortonworks/registry/pull/314
