### ISSUE TITLE
Expose more specific exceptions than just SerdesException

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#289]
Currently as a client the only exception throw in SerDes is a SerdesException, this makes it difficult/impossible for a client to understand the exception and handle it. 

E.g. If issue talking with SchemaRegistry, if the issue is simply IO / transitive the client may want to retry. Where as if the issue is with corrupted byte[] and simply cannot serialise into an Avro object a client may want to log error/alert and discard a poison message.

**Comment by michaelandrepearce** [comment]
@satishd there is one other issue is that SerDes exception does not extend SerializationException or RetriableException, this breaks some kafka contracts, are we ok with making SerDes extend this, or do we need for kafka serdes to catch and re-wrap again?

**Comment by satishd** [comment]
@michaelandrepearce SerDesException is generic and it is not related to Kafka. So, this should not extend any Kafka related exceptions. 
Kafka's Serializer/Deserializer interfaces does not declare any specific exceptions to be thrown. What contract are we breaking here?

**Comment by michaelandrepearce** [comment]
Their is an exception caller retriableexception which will cause a retry. Agreed they’re all runtime exceptions but it’s design decision they made in kafka , one I don’t like personally but it’s the way it’s done

**Comment by satishd** [comment]
Closing this issue as it is addressed by #290.
