### ISSUE TITLE
Registry UI Exception

### ISSUE THREAD

**Issue by gss2002** [hortonworks/registry#308]
When using the UI the following error is thrown causing the UI to stop functioning:

vendor.bundle.js:5 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at p._renderValidatedComponentWithoutOwnerOrContext (vendor.bundle.js:5)
    at p._renderValidatedComponent (vendor.bundle.js:5)
    at p._updateRenderedComponent (vendor.bundle.js:5)
    at p._performComponentUpdate (vendor.bundle.js:5)
    at p.updateComponent (vendor.bundle.js:5)
    at p.receiveComponent (vendor.bundle.js:5)
    at Object.receiveComponent (vendor.bundle.js:1)
    at Object.updateChildren (vendor.bundle.js:4)
    at v._reconcilerUpdateChildren (vendor.bundle.js:5)
    at v._updateChildren (vendor.bundle.js:5)
Promise rejected (async)
e @ application.js:23
e.notifyAll @ vendor.bundle.js:3
close @ vendor.bundle.js:6
closeAll @ vendor.bundle.js:2
perform @ vendor.bundle.js:2
u @ vendor.bundle.js:3
perform @ vendor.bundle.js:2
batchedUpdates @ vendor.bundle.js:5
a @ vendor.bundle.js:1
_renderNewRootComponent @ vendor.bundle.js:3
_renderSubtreeIntoContainer @ vendor.bundle.js:3
render @ vendor.bundle.js:3
(anonymous) @ application.js:32
t @ vendor.bundle.js:1
window.webpackJsonp @ vendor.bundle.js:1
(anonymous) @ application.js:1

**Comment by shahsank3t** [comment]
@gss2002 Have you built registry from the source or downloaded any particular version?

**Comment by gss2002** [comment]
@shahsank3t I tried to build from source using maven on RHEL/Centos7. This happens with both 0.3.0 build and 0.4.0 build. 

mvn package -DskipTests

When enabling webpack development I see the following:

  | printWarning | @ | warning.js:33
-- | -- | -- | --
  | warning | @ | warning.js:57
  | createElement | @ | ReactElementValidator.js:190
  | patchedCreateElement | @ | patch.dev.js:188
  | render | @ | SchemaInfoForm.jsx:236
  | render | @ | createPrototypeProxy.js:44
  | (anonymous) | @ | ReactCompositeComponent.js:793
  | measureLifeCyclePerf | @ | ReactCompositeComponent.js:73
  | _renderValidatedComponentWithoutOwnerOrContext | @ | ReactCompositeComponent.js:792
  | _renderValidatedComponent | @ | ReactCompositeComponent.js:819
  | performInitialMount | @ | ReactCompositeComponent.js:359
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | mountChildren | @ | ReactMultiChild.js:234
  | _createInitialChildren | @ | ReactDOMComponent.js:701
  | mountComponent | @ | ReactDOMComponent.js:520
  | mountComponent | @ | ReactReconciler.js:43
  | performInitialMount | @ | ReactCompositeComponent.js:368
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | mountChildren | @ | ReactMultiChild.js:234
  | _createInitialChildren | @ | ReactDOMComponent.js:701
  | mountComponent | @ | ReactDOMComponent.js:520
  | mountComponent | @ | ReactReconciler.js:43
  | mountChildren | @ | ReactMultiChild.js:234
  | _createInitialChildren | @ | ReactDOMComponent.js:701
  | mountComponent | @ | ReactDOMComponent.js:520
  | mountComponent | @ | ReactReconciler.js:43
  | mountChildren | @ | ReactMultiChild.js:234
  | _createInitialChildren | @ | ReactDOMComponent.js:701
  | mountComponent | @ | ReactDOMComponent.js:520
  | mountComponent | @ | ReactReconciler.js:43
  | performInitialMount | @ | ReactCompositeComponent.js:368
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | performInitialMount | @ | ReactCompositeComponent.js:368
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | performInitialMount | @ | ReactCompositeComponent.js:368
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | performInitialMount | @ | ReactCompositeComponent.js:368
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | mountChildren | @ | ReactMultiChild.js:234
  | _createInitialChildren | @ | ReactDOMComponent.js:701
  | mountComponent | @ | ReactDOMComponent.js:520
  | mountComponent | @ | ReactReconciler.js:43
  | performInitialMount | @ | ReactCompositeComponent.js:368
  | mountComponent | @ | ReactCompositeComponent.js:255
  | mountComponent | @ | ReactReconciler.js:43
  | mountComponentIntoNode | @ | ReactMount.js:102
  | perform | @ | Transaction.js:141
  | batchedMountComponentIntoNode | @ | ReactMount.js:124
  | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:58
  | batchedUpdates | @ | ReactUpdates.js:95
  | _renderNewRootComponent | @ | ReactMount.js:317
  | _renderSubtreeIntoContainer | @ | ReactMount.js:399
  | renderSubtreeIntoContainer | @ | ReactMount.js:340
  | Portal._this._renderOverlay | @ | LegacyPortal.js:75
  | componentDidMount | @ | LegacyPortal.js:97
  | (anonymous) | @ | ReactCompositeComponent.js:262
  | measureLifeCyclePerf | @ | ReactCompositeComponent.js:73
  | (anonymous) | @ | ReactCompositeComponent.js:261
  | notifyAll | @ | CallbackQueue.js:74
  | close | @ | ReactReconcileTransaction.js:78
  | closeAll | @ | Transaction.js:207
  | perform | @ | Transaction.js:154
  | perform | @ | Transaction.js:141
  | perform | @ | ReactUpdates.js:87
  | flushBatchedUpdates | @ | ReactUpdates.js:170
  | closeAll | @ | Transaction.js:207
  | perform | @ | Transaction.js:154
  | batchedUpdates | @ | ReactDefaultBatchingStrategy.js:60
  | batchedUpdates | @ | ReactUpdates.js:95
  | dispatchEvent | @ | ReactEventListener.js:145

**Comment by shahsank3t** [comment]
@gss2002 Thanks for the details, I'll take a look at it in a while.

**Comment by gss2002** [comment]
@shahsank3t found some more info.. When building on Centos7 and Rhel7 and OS X High Sierra I noticed the following vs the version pushed via the release here:

registry-0.4.0.tar.gz contains registry-webservice-0.4.0-SNAPSHOT.jar and it has more files than what I am getting when I build with maven. So the question is why are these missing??

Example:
[root@ha21t52nf goodjar]# diff -Naur /tmp/badfiles.txt /tmp/goodfiles.txt 
--- /tmp/badfiles.txt	2017-11-30 10:20:34.133443620 -0500
+++ /tmp/goodfiles.txt	2017-11-30 10:20:42.283499635 -0500
@@ -8,6 +8,7 @@
 images
 index.html
 js
+main.js
 styles
 
 ./assets/fonts:
@@ -30,11 +31,28 @@
 
 ./assets/styles:
 css
+fonts
 img
 
 ./assets/styles/css:
+bootstrap.css
+font-awesome.min.css
 style.css
 style.css.map
+theme.css
+toastr.min.css
+
+./assets/styles/fonts:
+fontawesome-webfont.eot
+fontawesome-webfont.svg
+fontawesome-webfont.ttf
+fontawesome-webfont.woff
+fontawesome-webfont.woff2
+glyphicons-halflings-regular.eot
+glyphicons-halflings-regular.svg
+glyphicons-halflings-regular.ttf
+glyphicons-halflings-regular.woff
+glyphicons-halflings-regular.woff2
 
 ./assets/styles/img:
 back-default.png

**Comment by gss2002** [comment]
Its definitely not packing up the files correctly.. Something specific with maven. I've tried with Maven 3.3.3, 3.3.9 and Maven 3.5.2 all with same issues along with Oracle JDK 8_102, 8_121 and 8_151.. All with same issue missing the files I list above from the diff.

unzip -t webservice/target/registry-webservice-0.4.0-SNAPSHOT.jar 
Archive:  webservice/target/registry-webservice-0.4.0-SNAPSHOT.jar
    testing: META-INF/                OK
    testing: META-INF/MANIFEST.MF     OK
    testing: assets/                  OK
    testing: assets/fonts/            OK
    testing: assets/images/           OK
    testing: assets/js/               OK
    testing: assets/styles/           OK
    testing: assets/styles/css/       OK
    testing: assets/styles/img/       OK
    testing: com/                     OK
    testing: com/hortonworks/         OK
    testing: com/hortonworks/registries/   OK
    testing: com/hortonworks/registries/ha/   OK
    testing: com/hortonworks/registries/ha/zk/   OK
    testing: com/hortonworks/registries/listeners/   OK
    testing: com/hortonworks/registries/webservice/   OK
    testing: assets/fonts/fontawesome-webfont.eot   OK
    testing: assets/fonts/fontawesome-webfont.ttf   OK
    testing: assets/fonts/fontawesome-webfont.woff   OK
    testing: assets/fonts/fontawesome-webfont.woff2   OK
    testing: assets/fonts/glyphicons-halflings-regular.eot   OK
    testing: assets/fonts/glyphicons-halflings-regular.ttf   OK
    testing: assets/fonts/glyphicons-halflings-regular.woff   OK
    testing: assets/fonts/glyphicons-halflings-regular.woff2   OK
    testing: assets/images/fontawesome-webfont.svg   OK
    testing: assets/images/glyphicons-halflings-regular.svg   OK
    testing: assets/index.html        OK
    testing: assets/js/application.js   OK
    testing: assets/js/vendor.bundle.js   OK
    testing: assets/styles/css/style.css   OK
    testing: assets/styles/css/style.css.map   OK
    testing: assets/styles/img/back-default.png   OK
    testing: assets/styles/img/data-not-found.jpg   OK
    testing: assets/styles/img/favicon.ico   OK
    testing: assets/styles/img/logo.png   OK
    testing: assets/styles/img/start-loader.gif   OK
    testing: com/hortonworks/registries/ha/zk/ZKLeadershipParticipant$1.class   OK
    testing: com/hortonworks/registries/ha/zk/ZKLeadershipParticipant.class   OK
    testing: com/hortonworks/registries/listeners/TransactionEventListener$UnitOfWorkEventListener.class   OK
    testing: com/hortonworks/registries/listeners/TransactionEventListener.class   OK
    testing: com/hortonworks/registries/webservice/RegistryApplication$1.class   OK
    testing: com/hortonworks/registries/webservice/RegistryApplication$2.class   OK
    testing: com/hortonworks/registries/webservice/RegistryApplication.class   OK
    testing: com/hortonworks/registries/webservice/RegistryConfiguration.class   OK
    testing: META-INF/maven/          OK
    testing: META-INF/maven/com.hortonworks.registries/   OK
    testing: META-INF/maven/com.hortonworks.registries/registry-webservice/   OK
    testing: META-INF/maven/com.hortonworks.registries/registry-webservice/pom.xml   OK
    testing: META-INF/maven/com.hortonworks.registries/registry-webservice/pom.properties   OK

**Comment by shahsank3t** [comment]
@gss2002 

> Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of SchemaFormContainer.

The above error is due to the version update of the react-select package to v1.1 whereas we need v1.0.0-rc.10.

0.3.0 build shouldn't have any such issues but 0.4.0 might have this since react-select's new version came out a couple of days before ours. I'll check that after creating a fix for this one.

**Comment by shahsank3t** [comment]
@gss2002 

> [root@ha21t52nf goodjar]# diff -Naur /tmp/badfiles.txt /tmp/goodfiles.txt

In the above command, badfiles.txt is the output of released build version (0.3.0 or 0.4.0) or your local build?

**Comment by gss2002** [comment]
0.4.0

**Comment by gss2002** [comment]
More info looks like something is definitely related to npm/node with maven as the sizes and output of the javascript is definitely different 

total 1212
-rw-r--r--. 1 root root  200899 Nov 21 09:22 vendor.bundle.js
-rw-r--r--. 1 root root 1032971 Nov 21 09:22 application.js
drwxr-xr-x. 6 root root      84 Nov 21 09:22 ..
drwxr-xr-x. 2 root root      50 Nov 21 09:22 .
[root@js]# pwd
/tmp/badjar/assets/js
[root@js]# ls -latr ../../../goodjar/assets/js/^C
total 1240
-rw-rw-r--. 1 root root  200790 Nov 30 09:04 vendor.bundle.js
-rw-rw-r--. 1 root root 1063012 Nov 30 09:04 application.js
drwxrwxr-x. 2 root root      50 Nov 30 09:04 .
drwxrwxr-x. 6 root root      84 Nov 30 11:07 ..

**Comment by shahsank3t** [comment]
@gss2002 
registry-0.4.0-src.zip? registry-0.4.0.zip? or Source code (zip)

> More info looks like something is definitely related to npm/node with maven as the sizes and output of the javascript is definitely different

It can differ based on when the packaging is done. The day when the released version was packaged, maybe react-select package (or some other) version was not updated(or updated to a certain version) and today when you building it locally, npm has downloaded the latest react-select package. Does it make sense?

**Comment by shahsank3t** [comment]
@gss2002 Raised PR https://github.com/hortonworks/registry/pull/310 to fix this.
You can try on your local with the fix and let me know if you still get an error.

@satishd - Days before we released 0.4.0 build, one of UI library (react-select) version for updated. For us, we already had the older version in our cache (node_modules/) and so it didn't matter but for any new user who builds (from the latest master or src build) will eventually end up getting latest version which breaks the UI. PR I have raised will fix that. 
I was wondering would you like (& how) to add this fix to 0.4.0 version since it breaks the UI completely (won't let a user add a schema). Your thoughts?

**Comment by gss2002** [comment]
I tried to build with this and it also fails because the zip doesn't contain node_modules.. This also happens with the 0.3.0 build also. Same issue
Just tried this
registry-0.4.0-src.zip

**Comment by gss2002** [comment]
@shahsank3t testing the fix now on 0.4.0 source

**Comment by gss2002** [comment]
@shahsank3t that patch fixes it for 0.4.0

**Comment by shahsank3t** [comment]
@gss2002 Great. Thanks for testing out the patch.
 
JFYI: node_modules is never present in any src builds. It gets created and has all the libraries downloaded when you build it.
And that's the very same reason why all the previous released source builds will fail since the newer version of a library (react-select to be precise in our current case) is breaking the existing UI.

**Comment by gss2002** [comment]
@shahsank3t thanks for helping resolve this so fast!! It's much appreciated and great work with Schema Registry so far! We have been using it with Nifi and Kafka

**Comment by satishd** [comment]
>@satishd - Days before we released 0.4.0 build, one of UI library (react-select) version for updated. For us, we already had the older version in our cache (node_modules/) and so it didn't matter but for any new user who builds (from the latest master or src build) will eventually end up getting latest version which breaks the UI. PR I have raised will fix that.
I was wondering would you like (& how) to add this fix to 0.4.0 version since it breaks the UI completely (won't let a user add a schema). Your thoughts?

@shahsank3t We should not update existing 0.4.0 modules but we need to have a hotfix kind of release(may be 0.4.1) to address this issue. We should make sure UI is tested in a clean environment before the release.

**Comment by shahsank3t** [comment]
@satishd This kind of issues tend to happen even if we test in a clean environment before releasing (only for users who build binaries from source).
Reason being in our package.json, we have auto-updating for few UI library and if those libs get update but fail to support backward compatibility, we run into such issues.

In the fix, I have fixed such lib version so we don't run into such issue again in future.

**Comment by satishd** [comment]
@gss2002 Thanks for reporting this issue. This will be part of 0.4.1 which will be released next week.
