### ISSUE TITLE
Modify existing APIs to support branching in UI

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/registry#325]
Expose/Modify below APIs to render "branching" support for UI

- **GET /schemas/{name}/branch** 
    Add this API to get all the branches that belong to a schema_name.
- **GET /schemas/aggregated**, **GET /schemas/{name}/aggregated** and **GET /search/schemas/aggregated**
    Modify these APIs to include branch info.

**Comment by satishwaghela** [comment]
Fixed this in PR https://github.com/hortonworks/registry/pull/329
