### ISSUE TITLE
Unable to build the schema registry 0.4.0

### ISSUE THREAD

**Issue by AnirudhNarasimhamurthy** [hortonworks/registry#327]
I cloned the registry repo and I am trying to build the registry repo with mvn. My build keeps failing to execute a goal on the project  schema-registry-webservice and it fails with the following error:

 Failed to execute goal on project schema-registry-webservice: Could not resolve dependencies for project com.hortonworks.registries:schema-registry-webservice:jar:0.4.0-SNAPSHOT: The following artifacts could not be resolved: io.confluent:kafka-avro-serializer:jar:3.1.1, io.confluent:kafka-schema-registry-client:jar:3.1.1, io.confluent:common-config:jar:3.1.1, io.confluent:common-utils:jar:3.1.1: Could not transfer artifact io.confluent:kafka-avro-serializer:jar:3.1.1 from/to hortonworks.repo (http://nexus-private.hortonworks.com/nexus/content/groups/public/): Failed to transfer file: http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1/kafka-avro-serializer-3.1.1.jar. Return code is: 503 , ReasonPhrase:Service Unavailable. -> [Help 1]

I tried doing a wget on the url for the kafka avro serializer and I am getting the following error:

wget http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1/kafka-avro-serializer-3.1.1.jar
--2017-12-11 23:59:56--  http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1/kafka-avro-serializer-3.1.1.jar
Resolving nexus-private.hortonworks.com... 54.173.242.72
Connecting to nexus-private.hortonworks.com|54.173.242.72|:80... connected.
HTTP request sent, awaiting response... 503 Service Unavailable
2017-12-11 23:59:57 ERROR 503: Service Unavailable.

Is this a case of confluent's kafka avro serializer jar's not being available or reachable at the specified url ? Are there any workarounds for this in order to build the schema registry project at this point in time. Our team at work, is looking at making some additional changes to the schema registry UI to support our use case and we are trying to get this packaged up and deployed to our dev environment. Before we start with the changes we wanted to make sure we can package and deploy this current project.

Any help in getting the build for schema registry to work correctly would be highly appreciated.

**Comment by satishd** [comment]
@AnirudhNarasimhamurthy I am able to access/download with that URL on my mobile n/w(without any Hortonworks network). Can you check whether you are able to access http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1 ?

**Comment by AnirudhNarasimhamurthy** [comment]
I can do a wget on http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1 and it returns me this --2017-12-12 08:42:33--  http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1
Resolving nexus-private.hortonworks.com... 54.173.242.72
Connecting to nexus-private.hortonworks.com|54.173.242.72|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1/ [following]
--2017-12-12 08:42:34--  http://nexus-private.hortonworks.com/nexus/content/groups/public/io/confluent/kafka-avro-serializer/3.1.1/
Reusing existing connection to nexus-private.hortonworks.com:80.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘3.1.1.1’

3.1.1.1                              [ <=>                                                     ]   3.40K  --.-KB/s    in 0s      

2017-12-12 08:42:34 (62.6 MB/s) - ‘3.1.1.1’ saved [3481]

But my build still fails with the same error as posted above. The kafka-avro-serializer-3.1.1.jar is getting a 503 when I am trying to fetch that.

**Comment by AnirudhNarasimhamurthy** [comment]
Thanks to @harshach suggestion, made a  change in the parent pom from
https://github.com/hortonworks/registry/blob/master/pom.xml#L587
to
http://repo.hortonworks.com/content/groups/public/ 

And that worked. I was able to get my build go through successfully.
