### ISSUE TITLE
Schema registry UI not loading and Error on proxy request when running from local machine

### ISSUE THREAD

**Issue by AnirudhNarasimhamurthy** [hortonworks/registry#330]
Hi,

I forked the registry project and I was able to get it built via mvn clean install.

I wanted to launch the schema registry UI from the registry repo code that I have on my local machine. I did the following:

1. Cd into the webservice/src/main/resources folder
2. Ran **npm install** to install all the dependencies. That worked fine
3. Ran **npm run build**. Worked fine
4. Issued **npm start**

And I got the following output on the console:

> registry@0.0.1 start /Users/anarasimhamurthy/registry/webservice/src/main/resources
> node dev-server.js

[HPM] Proxy created: [ '/api' ]  ->  http://localhost:9090

Webpack: 🚧  App is listening at http://localhost:9191
webpack built 1dbeb96d4bc25c7f1159 in 17277ms

I then tried accessing the app from the browser. When I did localhost:9191 I just see an empt white page. When I looked into the developer console, I see the following:

http://localhost:9191/ui/styles/css/style.css net::ERR_ABORTED
localhost/:40 GET http://localhost:9191/ui/js/vendor.bundle.js net::ERR_ABORTED
localhost/:41 GET http://localhost:9191/ui/js/application.js net::ERR_ABORTED
localhost/:41 GET http://localhost:9191/ui/js/application.js 404 (Not Found)

Also when I tried going to the localhost:9191/api endpoint I get the following error:

Error on proxy request
[HPM] Error occurred while trying to proxy request /api from localhost:9191 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)
Error on proxy request
[HPM] Error occurred while trying to proxy request /api from localhost:9191 to http://localhost:9090 (ECONNREFUSED) (https://nodejs.org/api/errors.html#errors_common_system_errors)

I also tried going to localhost:9090 and that doesn't resolve.

I guess I am definitely missing something or running it incorrectly. Is there a documentation on how to start the app and the UI from a cloned version of this project. Would really appreciate any timely help on this issue.

PS: I could get the schema registry UI to work via the downloaded distribution and starting up the registry server. I want to know what is the equivalent

**Comment by shahsank3t** [comment]
@AnirudhNarasimhamurthy @satishd 

>I also tried going to localhost:9090 and that doesn't resolve.

This could be the case due to admin port being 8081. If so, could be fixed with https://github.com/hortonworks/registry/issues/331

> When I did localhost:9191 I just see an empty white page. When I looked into the developer console, I see the following:
> 
> http://localhost:9191/ui/styles/css/style.css net::ERR_ABORTED
> localhost/:40 GET http://localhost:9191/ui/js/vendor.bundle.js net::ERR_ABORTED
> localhost/:41 GET http://localhost:9191/ui/js/application.js net::ERR_ABORTED
> localhost/:41 GET http://localhost:9191/ui/js/application.js 404 (Not Found)

Yes, this is an issue currently where /ui/ is not actually present while UI development. 
I'll work on the fix for this.

**Comment by satishd** [comment]
@shahsank3t Raised #332 to address #331, that can be merged once it is reviewed.

**Comment by satishwaghela** [comment]
@shahsank3t @satishd 
Raised PR https://github.com/hortonworks/registry/pull/333 for UI fixes

**Comment by shahsank3t** [comment]
@satishd I have reviewed #332 and #333 with the latest master branch and both fixes the issue 
@AnirudhNarasimhamurthy mentioned above.
