### ISSUE TITLE
Unable to upgrade from 0.3 to 0.4

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#335]
Currently 0.3 client doesn't ignore extra new fields in 0.4 as such upgrading a server causes all clients to fail.

There was the following change to ignore new fields, but it seems this wasn't made in 0.3 tag.

https://github.com/hortonworks/registry/commit/59a25398b3614242a92db7123d563fa5311ec369#diff-3438b2aaf742f7c026f1eec7e2ec29c1 

Essentially this needs to be put onto 0.3 branch and a point release done, to allow clients to change to 0.3.1 client (With this fix / change merged from master) then server can be upgraded to 0.4.

@satishd any chance this could be done e.g. a 0.3.1 release with this compatibility fix? We attempted an upgrade to 0.4 but hit this issue, due to the new fields in 0.4 , but 0.3 clients not ignoring.

**Comment by michaelandrepearce** [comment]
Looks like this is actually in, https://github.com/hortonworks/registry/tree/HDF-3.0.1.11.

**Comment by satishd** [comment]
>@satishd any chance this could be done e.g. a 0.3.1 release with this compatibility fix? We attempted an upgrade to 0.4 but hit this issue, due to the new fields in 0.4 , but 0.3 clients not ignoring.
@michaelandrepearce We can have 0.3.1 release to address this issue which maybe also useful to others in the community. I will raise PR and start release process soon.

**Comment by satishd** [comment]
@michaelandrepearce  Forked out 0.3.1-maint branch form HDF-3.0-maint which includes the required changes also. I hope this works for your case too.
I plan to send release mail tomorrow by having respective release draft for this branch.

**Comment by satishd** [comment]
@michaelandrepearce gentle reminder to go through my earlier comment. Plan to draft 0.3.1 release  once I get your confirmation.

**Comment by michaelandrepearce** [comment]
Sorry was off on holidays. LGTM

**Comment by satishd** [comment]
@michaelandrepearce Sent a vote mail on RC1 for 0.3.1 in mailing list(registry@googlegroups.com).

**Comment by michaelandrepearce** [comment]
@satishd 0.3.1 has disappeared from tags/releases
