### ISSUE TITLE
Deleting a schema branch with an enabled schema should throw BAD REQUEST error

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/registry#336]
Deleting a schema branch with an enabled schema version throws a BAD REQUEST error from the back end, but the error is not propagated to UI.

**Comment by satishwaghela** [comment]
Raised PR https://github.com/hortonworks/registry/pull/340 for UI - Showing error notification on BAD REQUEST.

**Comment by satishd** [comment]
Thanks @satishwaghela for addressing this issue.
