### ISSUE TITLE
SchemaRegistryClient#addSchemaVersion is backward incompatible as it is added with SchemaBranchNotFoundException.

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#337]
`SchemaRegistryClient#addSchemaVersion` is backward incompatible as it is added with SchemaBranchNotFoundException. `SchemaBranchNotFoundException` should be declared as RuntimeException to support backward compatible nature which got pointed out in review but it is missed in later commits while reviewing/merging.

**Comment by michaelandrepearce** [comment]
Should extend client specific rather than just runtime please

**Comment by satishd** [comment]
@michaelandrepearce This is not really specific to any ser/des APIs but a client API which receives `SchemaBranchNotFoundException` when that branch is not available. Can you be more descriptive on what you meant here?
