### ISSUE TITLE
BAD Request is not shown in UI if a schema version transition is made to a custom state

### ISSUE THREAD

**Issue by raju-saravanan** [hortonworks/registry#341]
When the below call is made
        **POST /schemas/versions/{id}/state/{stateId}**
if a bad request is thrown, the UI is not able to display the error.

**Comment by shahsank3t** [comment]
PR https://github.com/hortonworks/registry/pull/342 fixes this issue

**Comment by satishd** [comment]
Thanks @joylyn for fixing this issue with #342
