### ISSUE TITLE
DEFAULT_SCHEMA_CACHE_EXPIRY_INTERVAL_SECS is set to 300 ms

### ISSUE THREAD

**Issue by stiradrian** [hortonworks/registry#359]
The Horton SchemaRegistryClient is setting DEFAULT_SCHEMA_CACHE_EXPIRY_INTERVAL_SECS to a value of 300 ms and then assign it as default value for Configuration.SCHEMA_TEXT_CACHE_EXPIRY_INTERVAL_SECS.

In a streaming scenario, this expiration interval is to short.
Kafka producer will republish the schema on very short intervals creating a performance concern.

**Why the "_SECS" suffix if the value is used as TimeUnit.MILLISECONDS. Is this a bug and it should be TimeUnit.SECONDS instead?**

**If not a bug, why is expiration interval set so low?**

```java
public static final long DEFAULT_SCHEMA_CACHE_EXPIRY_INTERVAL_SECS = 5 * 60L;

public static final ConfigEntry<Number> SCHEMA_TEXT_CACHE_EXPIRY_INTERVAL_SECS =
                ConfigEntry.optional("schema.registry.client.schema.text.cache.expiry.interval.secs",
                                     Integer.class,
                                     "Expiry interval(in seconds) of an entry in schema text cache.",
                                     DEFAULT_SCHEMA_CACHE_EXPIRY_INTERVAL_SECS,
                                     ConfigEntry.PositiveNumberValidator.get());

schemaTextCache = CacheBuilder.newBuilder()
                .maximumSize(((Number) configuration.getValue(Configuration.SCHEMA_TEXT_CACHE_SIZE.name())).longValue())
                .expireAfterAccess(((Number) configuration.getValue(Configuration.SCHEMA_TEXT_CACHE_EXPIRY_INTERVAL_SECS.name())).longValue(),
                                   TimeUnit.MILLISECONDS)
                .build();
```

**Comment by satishd** [comment]
This is already fixed in latest master with 83f13d928ece3c3563dbc2a3da717eb91f8fb2f2.
