### ISSUE TITLE
SchemaVersionInfoCache configuration is set as millisecond instead of second

### ISSUE THREAD

**Issue by bf4688** [hortonworks/registry#368]
In SchemaRegistryClient, 

this.schemaVersionInfoCache = new SchemaVersionInfoCache(
...,
((Number)this.configuration.getValue(SchemaRegistryClient.Configuration.SCHEMA_VERSION_CACHE_SIZE.name())).longValue(), ((Number)this.configuration.getValue(SchemaRegistryClient.Configuration.SCHEMA_VERSION_CACHE_EXPIRY_INTERVAL_SECS.name())).longValue());

The schemaVersionInfoCache expiration parameter is read from Configuration.SCHEMA_VERSION_CACHE_EXPIRY_INTERVAL_SECS, which is in second unit (default to 300 seconds). 
However, in the SchemaVersionInfoCache class, that parameter is treated as millisecond, 
this.loadingCache = CacheBuilder.newBuilder().maximumSize(schemaCacheSize).expireAfterAccess(schemaCacheExpiryInMilliSecs, TimeUnit.MILLISECONDS).build(new CacheLoader<SchemaVersionInfoCache.Key, SchemaVersionInfo>() {
            public SchemaVersionInfo load(SchemaVersionInfoCache.Key key) throws Exception {...

This seems not right. It causes cache timeout being set at 300ms, which is way too short. 
Either SchemaRegistryClient should convert second into millisecond before calling SchemaVersionInfoCache or SchemaVersionInfoCache should change its timeunit from millisecond to second. 

Note our team at AT&T reported another similar issue, ISSUE-346, involving inconsistent interpretation of timeout values.

**Comment by satishd** [comment]
This is already fixed with 83f13d928ece3c3563dbc2a3da717eb91f8fb2f2. Please reopen if you are talking about a different issue.
