### ISSUE TITLE
Merging to master branch should lead to the merged/existing version.

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#370]
Merging a schema version can create a new version on master branch or it can return a schema version that already exists on master branch. UI should take it to the schema version of the merged result.

Merge API(with #366) returns merged result which has details like
- result schema version 
-  merge message. 

UI can show respective merge message instead of always showing "Merged successfully".

**Comment by satishd** [comment]
#366 is merged and it can be used to address this issue.

**Comment by shahsank3t** [comment]
https://github.com/hortonworks/registry/pull/371 fixes this
