### ISSUE TITLE
Provide helper utility for manual transaction handling

### ISSUE THREAD

**Issue by HeartSaVioR** [hortonworks/registry#381]
Recently Streamline encountered a blocker issue (https://github.com/hortonworks/streamline/issues/1157) which came from very silly mistake (patch: https://github.com/hortonworks/streamline/pull/1158).

This is the logic for handling with manual transaction (after applying fix):

```
    @FunctionalInterface
    interface ConsumerWithThrowsException<T> {
        void accept(T t) throws Exception;
    }

    private void mutateTopologyContext(ConsumerWithThrowsException<TopologyContext> mutatingFunction,
                                       TopologyContext topologyContext) throws Exception {
        boolean rolledBackTransaction = false;
        try {
            transactionManager.beginTransaction(TransactionIsolation.DEFAULT);
            mutatingFunction.accept(topologyContext);
        } catch (IgnoreTransactionRollbackException e) {
            throw convertThrowableToException(e.getCause());
        } catch (Throwable e) {
            transactionManager.rollbackTransaction();
            rolledBackTransaction = true;
            throw convertThrowableToException(e);
        } finally {
            if (!rolledBackTransaction) {
                transactionManager.commitTransaction();
            }
        }
    }

    private void mutateTopologyContext(ConsumerWithThrowsException<TopologyContext> mutatingFunction,
                                       Topology topology, String asUser) throws Exception {
        mutateTopologyContext(mutatingFunction, getTopologyContext(topology, asUser));
    }

```

which IgnoreTransactionRollbackException acts as a marker exception to guide that we should commit transaction instead of rolling back even exception occurs.

https://github.com/HeartSaVioR/streamline/blob/2a8c3ecb930f88211f20598d104a33aa9e8c88bd/common/src/main/java/com/hortonworks/streamline/common/exception/IgnoreTransactionRollbackException.java

We could generalize above code block and provide utility class which contains methods accepting some functional interfaces (like Consumer, Function, etc.) and handling manual transaction. It should help avoiding silly mistakes which affect really badly.

@satishd Do you think this issue is making sense to go with crafting and submitting a patch?

**Comment by arunmahadevan** [comment]
@HeartSaVioR , agree we can have a common utility that can be reused in streamline an elsewhere.

One suggestion is to reverse the logic so that we handle commit failures better. Something like -

```java
boolean committed = false;
try {
  transactionManager.beginTransaction(TransactionIsolation.DEFAULT);
  mutatingFunction.accept(topologyContext);
  transactionManager.commitTransaction();
  committed = true;
} catch (IgnoreTransactionRollbackException e) {
  transactionManager.commitTransaction();
  committed = true;  
  throw convertThrowableToException(e.getCause());
} finally {
  if (!committed) {
    transactionManager.rollbackTransaction();
  }
}
```

**Comment by HeartSaVioR** [comment]
@arunmahadevan posted a comment while I'm writing a comment. :)

So as we can find his logic above, @arunmahadevan found another bug on my logic unfortunately (when rollback throws Exception it reaches `finally` and commit) - which should be fixed in Streamline, again. ;(

His logic makes sense, but it only makes perfect sense when **TransactionManager.rollbackTransaction() guarantees the transaction will be always closed via rolled back manner**. TransactionManager.commitTransaction() doesn't need to do that, since we will try rollback after error.

If TransactionManager.rollbackTransaction() throws exception and leaves transaction opened, we should retry rollback until it succeeds (possibly infinite loop) to not make the transaction being leaked. Both situations should be really bothering.

So I think we should document the guarantee into TransactionManager interface, and let implementations guarantee it. Current implementation of TransactionManager leverages AbstractQueryExecutor which looks like guaranteeing this well, so for us that would be a matter of documentation.

More strictly, QueryExecutor interface should have such guarantee to let JdbcStorageManager guarantees same thing.

I'll craft a patch based on what I've described. Please provide opinions regarding my input. Thanks in advance!

**Comment by satishd** [comment]
@HeartSaVioR @arunmahadevan Makes sense to have this utility but it may need few changes and describe the contract as clear as possible. We may want to even take `isloationLevel` as one of the arguments.
Some drivers take care of any errors in commit to be rolledback before throwing error back to the caller but it is good to rollback any error thrown from commit also. I assume calling rollback again would not throw any errors.

We may have API in `TransactionManager` like below (with better names), which can be discussed and enhanced.
```
    <T, R> R runInTransaction(TransactionIsolation transactionIsolation, FunctionEx<T, R> fn, T t)
```

It seems @raju-saravanan had some API but he removed later when he raised PR as he may not have seen much usages.

When I saw https://github.com/hortonworks/streamline/issues/1157 , I thought StorageManager should get all open transactions and close them when StorageManager is closed so that you will not have any open locks. I will file respective issue and it will be addressed soon.
