### ISSUE TITLE
v0.5.0 removed from releases

### ISSUE THREAD

**Issue by dp435** [hortonworks/registry#407]
Also, downloads to assets on https://github.com/hortonworks/registry/releases/tag/v0.5.0 lead to a 404 error. It would be ideal if the binaries weren't removed.

@satishd It looks like v0.3.1 and v0.4.0 releases were removed as well.

**Comment by dp435** [comment]
@satishd It looks like v0.3.1 and v0.4.0 releases were removed as well.

**Comment by michaelandrepearce** [comment]
note this isn't the first time this occurred now. From a users perspective who needs to trust a tag is immutable artefact. Should be open to why is this occurring?

**Comment by satishd** [comment]
@dp435 @michaelandrepearce Our infra team is looking into the issue.

**Comment by gabriel9** [comment]
You are right, but if there is none and you need it just compile.

**Comment by michaelandrepearce** [comment]
@satishd any news? Or update

**Comment by michaelandrepearce** [comment]
@satishd i just logged in this evening and magically they're back... it seems this now is resolved....

**Comment by satishd** [comment]
@michaelandrepearce Our infra team restored them, thanks for your patience.

**Comment by michaelandrepearce** [comment]
@satishd thanks 👍 appreciated
