### ISSUE TITLE
Calling only addSchemaMetadata function causes Web GUI to indefinitely "load"

### ISSUE THREAD

**Issue by dp435** [hortonworks/registry#409]
In v0.5.0, adding only the schema metadata by calling addSchemaMetadata function defined in [SchemaRegistryClient.java](https://github.com/hortonworks/registry/blob/master/schema-registry/client/src/main/java/com/hortonworks/registries/schemaregistry/client/SchemaRegistryClient.java) causes the Web GUI to get indefinitely stuck in the loading screen after refreshing.

**Comment by gcsaba2** [comment]
Closed due to inactivity.
