### ISSUE TITLE
Client side schema validation - Disable or Customize

### ISSUE THREAD

**Issue by jdye64** [hortonworks/registry#415]
Currently there is no customizable way to way to either disable client side validation OR use a different method. If someone wants to add their own schema provider this is not possible because the client side code will not allow you to upload anything that is not validated as JSON. This prevents any of the data from being sent to the server side for further validation.

**Comment by satishd** [comment]
@shahsank3t Default implementation for avro schema provider with json validation for schema payloads can be extracted. There need to be pluggable validation for respective schema providers. Any new schema provider(like XML schemas) can provide respective validation to UI.

**Comment by shahsank3t** [comment]
https://github.com/hortonworks/registry/pull/416 fixes this
