### ISSUE TITLE
Registry drop-tables.sql is empty we should be able to clean the database.

### ISSUE THREAD

**Issue by harshach** [hortonworks/registry#43]

**Comment by satishd** [comment]
[drop_schemaregistry-tables.sql](https://github.com/hortonworks/registry/blob/master/schema-registry/core/src/main/resources/mysql/drop_schemaregistry-tables.sql) contains the script but [drop_tables.sql](https://github.com/hortonworks/registry/blob/master/bootstrap/sql/mysql/drop_tables.sql) is missing the same.

**Comment by satishd** [comment]
@harshach You may want to close this issue as PR #44 addresses the same.
