### ISSUE TITLE
2 schema versions with the same schemaText

### ISSUE THREAD

**Issue by burandobata** [hortonworks/registry#430]
Hey,

I've got following warnings in application logs:
```
WARN  [2018-03-27 09:23:42,216] com.hortonworks.registries.schemaregistry.SchemaVersionLifecycleManager: Exists more than one schema with schemaMetadataName: [xxxxxx] and schemaText [{...}]
``` 

I've upgraded this environment today from 0.3 to 0.5.1 and the error is still there.

As I've found inside our database, we have couple of schemas with the same schemaText field in schema_version_info table for different schema versions. The service should have attributed the same schemaText to the same version of a schema. I'm not sure how/why it happened. Based on timestamps in db those schema versions with the same schemaText has been created within couple of ms window. This has happened while we were running 0.3. We are running 2 schema registry services on independent boxes using the same postgres backend.

I have 2 questions here:
1. Is this a known bug? If so is 0.5.1 still affected?
2. How can I deal with current situation?

thanks,
Marek

**Comment by gcsaba2** [comment]
Closed due to inactivity.
