### ISSUE TITLE
Provide JMS Integration

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#435]
This is to be similar to Kafka , where given an Object it uses avro serialisation to bytes. 
In case of JMS this means taking the Object set in JMSObjectMessage and serialize it internally to JMSBytesMessage. 

Overriding providers like ActiveMQ, Qpid JMS, etc, which just java serialize ObjectMessage. 

I will be contributing this, we have been using it for a while internally, so please don't implement @harshach , @satishd :) ,  I will hopefully raise PR in the next week.

**Comment by michaelandrepearce** [comment]
@harshach @satishd delayed due to personal reasons, will get on to this soon.

**Comment by gcsaba2** [comment]
Closed due to inactivity.
