### ISSUE TITLE
UI hangs if schemaBranches is empty

### ISSUE THREAD

**Issue by oscarandreu** [hortonworks/registry#438]
If a given schema have it branches empty the UI is unable to load.
The problem is that the schemaBranches property is being used without any previous check giving the next error:
TypeError: Cannot read property 'schemaVersionInfos' of undefined
    at new t (application.js:23)

To reproduce the error only need a clean HDF sandbox and execute this:
`curl -X DELETE 'http://127.0.0.1:7788/api/v1/schemaregistry/schemas/trucking_data_traffic:v/versions/1'`

**Comment by oscarandreu** [comment]
I did it directly from the database.

**Comment by gcsaba2** [comment]
Closed due to inactivity.
