### ISSUE TITLE
Format of input files for TruckEventsKafkaAvroSerDesApp.java

### ISSUE THREAD

**Issue by sunnypatel2141** [hortonworks/registry#440]
I'm looking at the TruckEventsKafkaAvroSerDesApp.java example provided in registry/examples/schema-registry/avro/src/main/java/com/hortonworks/registries/schemaregistry/examples/avro/ folder. 

Looking at the java file, there are three parameters that need to be specified:
                    -d or --data-file
                    -s or --schema-file
                    -p or --producer-config

I am slightly confused as to the format of these files, and their extensions as well. Is this documented somewhere, if so please provide the link to it.

Is the schema-file format supposed to be: schema.registry.url=http://localhost:8081 ? What about producer-config ?

Thank you.

**Comment by gcsaba2** [comment]
Closed due to inactivity.
