### ISSUE TITLE
HA implementation through JDBC (MySQL or PostgreSQL)

### ISSUE THREAD

**Issue by joanvr** [hortonworks/registry#446]
Although it really makes sense to use ZK to coordinate HA leadership, given we already need it for Kafka, sometimes we may not have access to ZK, or we may have a shared registry across different environments and it doesn't make sense to tie it to any specific one.
Taking into consideration that we already have a Storage dependency on MySQL or PostgreSQL, it makes sense to also coordinate HA leadership through it.

**Comment by joanvr** [comment]
Implementation on #445

**Comment by michaelandrepearce** [comment]
There is no need to have a single leader if using a db backend. You can run multi master as db will be transactional anyhow
