### ISSUE TITLE
Change JWTAuthenticationHandler to only support SSO

### ISSUE THREAD

**Issue by priyank5485** [hortonworks/registry#447]
Currently the JWTAuthenticationHandler is implemented as an alternate to Kerberos where it will kick in only based on user-agent based setting and go to Kerberos otherwise. This creates problems because in a non kerberized cluster HTTP principal needed by the base class is not available. This change is forces SSO for all requests and de-couples it from Kerberos

**Comment by priyank5485** [comment]
https://github.com/hortonworks/registry/pull/448

**Comment by priyank5485** [comment]
@satishd Still need to test this. Please don't merge

**Comment by satishd** [comment]
Closing this as https://github.com/hortonworks/registry/pull/448#issuecomment-394463025 it is verified.
