### ISSUE TITLE
Schema registry UI not responding while adding schemas

### ISSUE THREAD

**Issue by satishd** [hortonworks/registry#45]

**Comment by shahsank3t** [comment]
I am using the attached patch with the latest master and on adding a new schema, I am getting error:
`{"responseCode":1102,"responseMessage":"An exception with message [java.sql.SQLIntegrityConstraintViolationException: (conn:13892) Column 'schemaInstanceId' cannot be null\nQuery is: INSERT INTO schema_field_info (`id`, `schemaInstanceId`, `fieldNamespace`, `name`, `type`, `timestamp`) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE `id` = ?, `schemaInstanceId` = ?, `fieldNamespace` = ?, `name` = ?, `type` = ?, `timestamp` = ?, parameters [<null>,<null>,<null>,'driverId123','INT',1488438288673,<null>,<null>,<null>,'driverId123','INT',1488438288673]] was thrown while processing request. Please check webservice/ErrorCodes.md for more details."}`

[0001-changed-registry-UI-as-per-the-new-mocks.patch.zip](https://github.com/hortonworks/registry/files/812980/0001-changed-registry-UI-as-per-the-new-mocks.patch.zip)

**Comment by satishd** [comment]
I will try out the UI patch uploaded by @shahsank3t and look into the backend issue.

**Comment by satishd** [comment]
@shahsank3t I am able to run UI patch on my latest master at [b2ce9aa](b2ce9aa6c73ed5df17e95116253d9c0703f4a1a9) without any issues.
