### ISSUE TITLE
On Confluent API, the POST method /api/v1/confluent/subjects/{subject} only works for MASTER branch

### ISSUE THREAD

**Issue by joanvr** [hortonworks/registry#450]
When asking the versions of a subject with GET /api/v1/confluent/subjects/{subject}/versions all the version ids on all branches are returned.
When querying the versions with GET /api/v1/confluent/subjects/{subject}/versions/{versionId} all the versions work (no matter on which branch too).
When querying by the id with GET /api/v1/confluent/schemas/ids/{id} all the schemas can be queried no matter the branch too.

It makes sense that when using POST /api/v1/confluent/subjects/{subject}/versions all the schemas are registered on MASTER branch, since the confluent registry doesn't have the concept of branches.

BUT, when using the method POST /api/v1/confluent/subjects/{subject} to gather the ID given an schema without registering them if non existant, it should look up to all branches, not only MASTER, to be consistent with all other methods, and to make the client able to discover schemas already registered in other branches.

**Comment by gcsaba2** [comment]
Closed due to inactivity
