### ISSUE TITLE
Cannot create client if there is resteasy dependency

### ISSUE THREAD

**Issue by ngorchakova** [hortonworks/registry#465]
if there is a dependency on org.jboss.resteasy:resteasy-jaxrs, the schema registry client cannot be created

it is failing on (class com.hortonworks.registries.schemaregistry.client.SchemaRegistryClient)

>this.client = ((ClientBuilder)ClientBuilder.newBuilder().withConfig(config).property("jersey.config.client.followRedirects", Boolean.TRUE)).build();
>this.client.register(MultiPartFeature.class);

As client created not as a JerseyClient , but as a ResteasyClient. MultiPartFeature is a specific feature of jersey client. And registration of it in resteasy client doesn't work. 

Possible solution: replace with JerseyClientBuilder instead of ClientBuilder, to be sure that jersey client is created

**Comment by ngorchakova** [comment]
Hi,
unfortunately, the fix I provided in PR: https://github.com/hortonworks/registry/pull/469 didn't work. Mostly it didn't change anything, as JerseyClientBuilder.newBuilder() is inherited from ClientBuilder.newBuilder()

the proper fix is to use new JerseyClientBuilder().
we tested it on our code and proved that it was working. Would you like me to raise a one more PR?

**Comment by gcsaba2** [comment]
Done
