### ISSUE TITLE
Docker Images?

### ISSUE THREAD

**Issue by gaving** [hortonworks/registry#504]
Are there any official docker containers for registry?

Keen to start using it with NiFi but I can only find https://github.com/TheBookPeople/hortonworks-registry-docker which seems pretty outdated.

**Comment by satishd** [comment]
https://github.com/hortonworks/registry/tree/master/docker may be useful.

**Comment by gaving** [comment]
Hi satishd!

Thanks, I did see that but got a bit overwhelmed. 🤕 

My current plan is to pull down https://github.com/TheBookPeople/hortonworks-registry-docker/pull/2 to build the image myself and see how I get on with it.
