### ISSUE TITLE
Changes for ISSUE-88 breaks schema that contains union with self reference.

### ISSUE THREAD

**Issue by potatop** [hortonworks/registry#533]
With version 0.5.4. Import of following schema fails with error `org.apache.avro.SchemaParseException: Can't redefine: com.hortonworks.types.node`
```
{
  "name": "node",
  "namespace": "com.hortonworks.types",
  "type": "record",
  "fields": [
    {
      "name": "data",
      "type":  [
        "null",
        "long"
      ]
    },
    {
      "name": "next",
      "type": [
        "null",
        "com.hortonworks.types.node"
      ]
    }
  ]
}
```
This is caused by changes introduced in #88 in `handleUnionFieldsWithNull()`, new fields with default values are created with the old schema object and not the new schema object.

**Comment by gcsaba2** [comment]
Closed due to inactivity, we use avro 1.11 currently.
