### ISSUE TITLE
Support for transitive check

### ISSUE THREAD

**Issue by mdeknowis** [hortonworks/registry#549]
Currently the hortenworks schema does only support "simple" compatible checks. But as  confluent states, there are also use cases to support transitive checks:

- https://docs.confluent.io/current/schema-registry/avro.html#order-of-upgrading-clients
- https://docs.confluent.io/current/schema-registry/avro.html#transitive-property

So for example in case of forward compatible:

```json
// v1
{
 "type": "record",
 "namespace": "foobar",
 "name": "TransitiveCheck",
 "fields": [
  {
   "name": "f0",
   "type": "int",
   "default": 1
  }
 ]
}

// v2
{
 "type": "record",
 "namespace": "foobar",
 "name": "TransitiveCheck",
 "fields": [
  {
   "name": "f1",
   "type": "int",
   "default": 1
  }
 ]
}

// v3
{
 "type": "record",
 "namespace": "foobar",
 "name": "TransitiveCheck",
 "fields": [
  {
   "name": "f1",
   "type": "int"
  }
 ]
}
```

So v2 is compatible to v1 and v3 is compatible to v2. But v3 is not compatible to v1.

So to ensure, that also v3 is compatible to v1, a transitive check would be required, so hortenworks registry also checks the new version against all (enabled) previous versions.

**Comment by cgumpert** [comment]
I support the feature request for having transitive compatibility checks, but I am wondering about your example. IMHO data produced with v3 can still be read with schema v1. Therefore, schema v3 should be forward compatible with schema v1.

**Comment by mdeknowis** [comment]
Might be, that I'm mixing up forward and backward. If so, I'm sorry, then replace forward by backward.

**Comment by gcsaba2** [comment]
Done
