### ISSUE TITLE
Kerberos relogin thread should not exit on error

### ISSUE THREAD

**Issue by turcsanyip** [hortonworks/registry#576]
If the Kerberos ticket refresh thread fails, it exits and never tries again (`KerberosLogin.spawnReloginThread()`).
It can happen due to a temporary error (eg. network problems), but as the thread exited, the registry client cannot recover. The kerberos login / refresh thread initiated in a static initializer block in `SchemaRegistryClient`, so JVM restart is needed in this case.

I would suggest to retry the login in the relogin thread (with some backoff) instead of simply exiting.

**Comment by gcsaba2** [comment]
Fixed
