### ISSUE TITLE
Schema Registry should allow schema registry clients to handle schema identifier and version tracking on their own

### ISSUE THREAD

**Issue by harshach** [hortonworks/registry#58]
The idea is that some well-behaved schema registry clients do not need/want the SR library to do the serialization and deserialization of the data for them and instead want the schema registry to primarily focus on the publishing/retrieval of the schemas themselves.
Today the schema registry client takes care of the serialization and deserialization of data, and when it does so, it will write out the identifier and version then write out the raw data.
So, for example, the resulting bytes on disk would be
<<identifier><version><whatever the raw data was>>
NiFi and protocols like JMS, HTTP, etc.. have facilities to support context (headers) and content (payload). So we don't need/want serializers to write that stuff for us, and we'll handle passing those references around for the objects.

**Comment by satishd** [comment]
Raised PR #63 for addressing this issue.
