### ISSUE TITLE
Schema registry breaks with MySql 8.0.11 

### ISSUE THREAD

**Issue by nikitap95** [hortonworks/registry#630]
I have updated my MySql from 5.7 to 8.0. Im using schema registry version 0.7.0

I have updated my bootstrap file to use "mysql-connector-java-8.0.11.zip". I also made changes to the registry.yaml file to use the `com.mysql.cj.jdbc.MysqlDataSource` instead of `com.mysql.jdbc.jdbc2.optional.MysqlDataSource`

However, I face the following issue : 

`Caused by: java.lang.ClassNotFoundException: com.mysql.cj.jdbc.Driver
hortonworks_schema | 	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
hortonworks_schema | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
hortonworks_schema | 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
hortonworks_schema | 	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
hortonworks_schema | 	at java.lang.Class.forName0(Native Method)
hortonworks_schema | 	at java.lang.Class.forName(Class.java:348)
hortonworks_schema | 	at org.flywaydb.core.internal.util.ClassUtils.instantiate(ClassUtils.java:59)
hortonworks_schema | 	... 5 more`

this is because I'm assuming the JDBC driver class uses `com.mysql.jdbc.Driver` instead of `com.mysql.cj.jdbc.Driver`

**Comment by leiwangouc** [comment]
I face the same problem.

Change mysql-connector-java-5.1.40.zip to mysql-connector-java-5.1.48.zip instead of 8.0.11 and have a try again

Also, In MySQL 8，if a table has foreign key, the referenced table must has INDEX.  Some create table will fail in MySQL 8

**Comment by nikitap95** [comment]
@leiwangouc 
I can't find a connector for mysql-connector-java-5.1.48.zip. Was the version of the connector something else?
