### ISSUE TITLE
Could not initailize the backend database when using  MySQL 8 

### ISSUE THREAD

**Issue by leiwangouc** [hortonworks/registry#642]
org.flywaydb.core.internal.exception.FlywaySqlException: 
Unable to obtain connection from database (jdbc:mysql://rm-uf6y06352cm11ti1s.mysql.rds.aliyuncs.com/schema_registry) for user 'schema_registry': Unknown system variable 'query_cache_size'

SQL State  : HY000
Error Code : 1193
Message    : Unknown system variable 'query_cache_size'

**Comment by gcsaba2** [comment]
This should work now since we do support Mariadb 10.5 which is compatible with MySql 8
