### ISSUE TITLE
Settings "avro.specific.reader" via Spring results in a class cast exception

### ISSUE THREAD

**Issue by gonozalviii** [hortonworks/registry#648]
AbstractAvroSnapshotDeserializer assumes type boolean for the property entry in its config map.
It uses the following line in its `doInit()`-Method

`useSpecificAvroReader = (boolean) getValue(config, SPECIFIC_AVRO_READER, false);`

Settings this property using Spring results in its type being a String. Changing that to:

`useSpecificAvroReader = Boolean.valueOf(getValue(config, SPECIFIC_AVRO_READER, false));`

would fix the issue.

**Comment by raju-saravanan** [comment]
@gonozalviii: Can you raise a PR for this?

**Comment by jay-blanc** [comment]
I'm facing the same issue, using com.hortonworks.registries.schemaregistry.serdes.avro.kafka.KafkaAvroDeserializer with Spring Boot.

As mentioned by @gonozalviii , would it be possible to get the given fix for this ?

**Comment by piecho1991** [comment]
@raju-saravanan PR: https://github.com/hortonworks/registry/pull/730

**Comment by gcsaba2** [comment]
Fixed.
