### ISSUE TITLE
Schema registry UI is very slow at initial load

### ISSUE THREAD

**Issue by nextropia** [hortonworks/registry#67]
In our environment it takes about 30 seconds for the UI to get populated with all the schemas in the registry.

Initially the screen displays "No data found" and then the schemas start to trickle in slowly.

It would be helpful to display some indication that the schemas are still being loaded. It would also be nice to speed up the loading if possible.

**Comment by shahsank3t** [comment]
@nextropia - Thanks for pointing out the performance issue.

@satishd - We might need to make some API modification for UI to get all the schema information, with its metadata and version in a single API request.

Currently, we are hitting following requests:

1. schemas - to get all the schema
2. schemas/:schemaName - to get metadata for ":schemaName" (We hit this API for as many schema's present)
3. schemas/:schemaName/versions - to get all version for ":schemaName" (We hit this API for as many schema's present)

Assuming, we have 5 schemas, UI is making 11 API calls which get's on increasing.

Can we have another simple GET ALL API that gathers all this data in the backend for all schema present and return the complete response?
It should reduce a significant amount of time I guess.

cc: @harshach - What do you think?

I'll also fix the initial "No data found" and show loading indication.

**Comment by satishd** [comment]
@shahsank3t I think we should not get all the data in one api call which may be heavy and  unnecessary. We can get schemas with basic metadata without versions. 

Multiple ways to fetch individual schema versions
 - Respective schema versions can be fetched when user clicks on any particular schema. 
 - Get schema versions which are visible within the window. We can have new api to get versions of given schemas.

All this data can be cached locally as this is not going to be modified.

**Comment by shahsank3t** [comment]
@satishd Sure, having a 2 API's (Schema + metadata & Version separate) will work. 

I think adding "id", "timestamp" & "versionCount" for every schema metadata and fixing "description" which is also set to null for "schemas" API, should be the only change needed from the backend.

**Comment by harshach** [comment]
@shahsank3t how about we display the metadata first and upon clicking to expand the schema we make a call to fetch the schema text?

**Comment by shahsank3t** [comment]
@harshach yup that's the plan now. Once we have the changes I mentioned in my previous comment, I'll do rest of the changes on the UI.

**Comment by nextropia** [comment]
Thanks guys, that sounds like a great plan!

**Comment by satishd** [comment]
Discussed with @shahsank3t, no need to add any backend apis and existing apis are sufficient to resolve the issue.

**Comment by shahsank3t** [comment]
PR https://github.com/hortonworks/registry/pull/75 is raised for this issue.
