### ISSUE TITLE
Missing docs?

### ISSUE THREAD

**Issue by DwaneHall** [hortonworks/registry#702]
Hey guys I'm not sure if you've noticed but the registry documentation seems to be experiencing a few issues (https://registry-project.readthedocs.io/en/latest/schema-registry.html#quickstart).  Not sure if it's been moved and the link not updated on the README page or there are hosting issues.

**Comment by raju-saravanan** [comment]
@DwaneHall : There some hosting issues. We fixed it now.

**Comment by DwaneHall** [comment]
Thanks @raju-saravanan!
