### ISSUE TITLE
Upgrade to Dropwizard 1.3.22

### ISSUE THREAD

**Issue by viktorsomogyi** [hortonworks/registry#707]
With 1.3.22 we also get a Jetty version bump from 9.4.11.v20180605 to 9.4.18.v20190429 which is a much newer version. It also synchronizes with SMM to allow easier dependency management.

Will also upgrade dependant libraries used by Dropwizard:
* jersey: 2.22.1 -> 2.25.1
* commons-lang3: 3.4 -> 3.8.1
* httpclient: 4.5.3 -> 4.5.7
* use jetty 9.4.18.v20190429 everywhere so it's consistent across the project
* dropwizard metrics-annotations 3.1.2 -> 4.0.5

**Comment by viktorsomogyi** [comment]
Will also upgrade dependant libraries used by Dropwizard:
* jersey: 2.22.1 -> 2.25.1
* commons-lang3: 3.4 -> 3.8.1
* httpclient: 4.5.3 -> 4.5.7

**Comment by gcsaba2** [comment]
Done
