### ISSUE TITLE
Simplifying the hadoop related dependencies

### ISSUE THREAD

**Issue by guruchai** [hortonworks/registry#711]
"registry-common" has dependencies on hadoop-client, hadoop-aws, hadoop-azure.... Wherever registry-common, all these dependencies get along as transitive dependencies. Some of these dependencies need to be pruned out.

**Comment by guruchai** [comment]
Clients that use authorization-agent should not depend on hadoop library for Authorization exception.

**Comment by gcsaba2** [comment]
Done.
