### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by nikitap95** [hortonworks/registry#729]
I'm using schema registry 0.7.0. On my production system, I see the memory of the pods increasing and eventually causing an OOM restart. 

Load is not very high, we are serving 60-100 requests every minute. The memory limit is 1200M and the memory consumption increases very gradually. 

It takes 48-50 hours for a restart, the memory keeps increasing gradually and never comes down. Is there a possible memory leak because everything else seems ok to me?

**Comment by gcsaba2** [comment]
Closing because the ticket is inactive for 2 years.
