### ISSUE TITLE
Documentation link - Sorry this page does not exist yet.

### ISSUE THREAD

**Issue by michaelandrepearce** [hortonworks/registry#82]
The link to documentation
http://registry-project.readthedocs.io/en/latest/

currently leads to no documentation.

<img width="791" alt="screen shot 2017-05-03 at 13 09 44" src="https://cloud.githubusercontent.com/assets/1387822/25659911/db27bf32-3001-11e7-859f-a6e0ba8458a4.png">

**Comment by harshach** [comment]
Thanks for reporting this @michaelandrepearce . Its broken due to markdown , working on fixing it.

**Comment by harshach** [comment]
Merged in changes . http://registry-project.readthedocs.io/en/latest/
