### ISSUE TITLE
Change the UI to add schema for better UX experience

### ISSUE THREAD

**Issue by shahsank3t** [hortonworks/registry#85]
Need to change the styling while adding a schema as per attached images.
![170504-add-schema-01](https://cloud.githubusercontent.com/assets/6761317/25744619/8147c224-31b8-11e7-894c-7efb4cfedbd4.png)

![170504-add-schema-02](https://cloud.githubusercontent.com/assets/6761317/25744621/821aa23e-31b8-11e7-8981-628eaa4429ed.png)

**Comment by satishwaghela** [comment]
PR - https://github.com/hortonworks/registry/pull/86 created to address this issue
